languageCode = "en-us"
title = "Espen Braastad"
theme = "custom"

[Author]
name = "Espen Braastad"

#[Permalinks]
#post = "/post/:year/:month/:filename/"
#code = "/:filename/"

[params]
github = "https://github.com/espebra"
disqus = "espenbraastad"

