languageCode = "en-us"
title = "Espen Braastad"
baseurl = "http://www.espenbraastad.no/"

[Author]
name = "Espen Braastad"

#[Permalinks]
#post = "/posts/:year/:month/:filename/"
#code = "/:filename/"

[params]
github = "https://github.com/espebra"
disqus = "espenbraastad"

